### ISSUE TITLE
User Story - Ordering allocated books online

### ISSUE THREAD

**Issue by Rhema28** [Rhema28/Premier-Agile-Project#2]
As a **primary teacher** I can **order the correct books online for my students** so that **they arrive in time for the beginning of term.**

**Acceptance Criteria:**
1. Create a catalogue of books arranged in order of ages and reading ability levels
2. Set a list of delivery or collection locations
3. Create an option box in which users can enter their desired delivery date.

#Tasks
- [ ] Choose the levels of the books
- [ ] Arrange the delivery locations in order of area
- [ ] Allow users to choose between collection or delivery
- [ ] Allow users to choose next day delivery or standard delivery option 
- [ ] Create hyperlink that takes you to return delivery address page and steps to take when returning items
